export const skills = [
  { img: '../icons8-aws-144.png', name: 'Amazon Web Services' },
  { img: '../Bootstrap_logo.svg.png', name: 'Bootstrap' },
  { img: '../icons8-chrome-web-store-144.png', name: 'Chrome Extensions' },
  { img: '../icons8-css3-144.png', name: 'CSS' },
  { img: '../icons8-docker-144.png', name: 'Docker' },
  { img: '../icons8-github-144.png', name: 'GitHub' },
  { img: '../icons8-graphql-144.png', name: 'GraphQL' },
  { img: '../icons8-html-5-144.png', name: 'HTML' },
  { img: '../icons8-javascript-144.png', name: 'JavaScript' },
  { img: '../icons8-mongodb-144.png', name: 'MongoDB' },
  { img: '../icons8-nodejs-144.png', name: 'NodeJS' },
  { img: '../icons8-npm-144.png', name: 'NPM' },
  { img: '../icons8-chatgpt-144.png', name: 'OpenAI API' },
  { img: '../icons8-postgresql-144.png', name: 'PostgreSQL' },
  { img: '../icons8-react-native-144.png', name: 'React' },
  { img: '../icons8-sass-144.png', name: 'Sass' },
  { img: '../icons8-stripe-144.png', name: 'Stripe' },
  { img: '../icons8-tailwindcss-144.png', name: 'TailwindCSS' },
  { img: '../icons8-typescript-144.png', name: 'TypeScript' },
];
