export const skills = [
  '../src/assets/icons8-html-5-144.png',
  '../src/assets/icons8-css3-144.png',
  '../src/assets/icons8-javascript-144.png',
  '../src/assets/icons8-typescript-144.png',
  '../src/assets/icons8-react-native-144.png',
  '../src/assets/icons8-mongodb-144.png',
  '../src/assets/icons8-nodejs-144.png',
  '../src/assets/icons8-npm-144.png',
  '../src/assets/icons8-tailwindcss-144.png',
  '../src/assets/icons8-github-144.png',
  '../src/assets/icons8-chatgpt-144.png',
  '../src/assets/icons8-stripe-144.png',
  '../src/assets/Bootstrap_logo.svg.png',
];
